---
title: "Health Analytics for Robust Policy"  
subtitle: "A Guide to Style" 
date: 'September 25, 2023' 
output: 
  html_document: 
    theme: sandstone 
bibliography: "refs.bib" 
csl: "plos.csl" 
---

***

[HARP](index.html) $\leftrightarrow$ [HUB](hub.html)

*** 

# {.tabset .tabset-fade .tabset-pills}

## Look and Feel  

+ The `html` pages are generated from R Markdown documents: `pagename.html` is generated by `pagename.Rmd`  

+ The banner at the top should include links to the [HARP](index.html) landing page, the navigation [HUB](hub.html), and (possibly) other closely related pages. 

+ The sections use tabset to make the material easy to access. Please use the command `{.tabset .tabset-fade .tabset-pills}` 


+ The `sandstone` theme is used throughout.  

## Writing Style 

+ `HARP` is a good place to introduce hard concepts in plain language. We hope to emulate the writing style of _Numerical Recipes in C._ In the preface to the $2^{nd}$ edition, the authors described their style in the $1^{st}$ edition as *``...informal, fearlessly editorial, unesoteric, and above all useful.''* 

+ The intent of `HARP` is to introduce complex concepts, so please keep it short and aim for one of the following: 

    - lecture notes
    
    - a user’s guide
    
    - a vignettes that teach a single concept
    
    - insightful commentary
    
+ If a document is getting too long and complex, consider splitting it up.  

+  Publish the long version, write the short version here, and add citations. In general, we don't want long essays or drafts. 

+ We think academic journals are the best place to put complex analyses, or discussions of highly technical material. Any new methods and new concepts should go through peer review.  

+ Please use the functionality to embed instructive R-code: 

```{r}
x = seq(-3, 3, length.out=200)
plot(x, x^2-4, type = "l", ylab = expression(x^2-4))
segments(-3, 0, 3, 0, col = grey(0.8))
```


## Citations 

+ References are strongly encouraged. The bibliography is `refs.bib` using the `plos` citation style. To add a citiation, use `[@cite-key]`. 

+ If there are any references, the last tab should be called `Refs`. For example, this is a citation to *Malaria: Principles and Practice of Malariology* [@WernsdorferWH1988MalariaPrinciples]. 

+ If you want to cite something but you can't find it in `refs.bib,` tell Dave it's missing and send a link.

## Refs 
