---
title: "HARP" 
subtitle: "Health Analytics for Robust Policy"  
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    theme: sandstone 
bibliography: "refs.bib" 
csl: "plos.csl" 
---

***

[HUB](hub.html)

*** 

# {.tabset .tabset-fade .tabset-pills}

## -  

Science and policy are important activities that involve analysis and inference, but while science is about knowing, policy is about doing. Policy should use the best science available, but even if evidence is weak, a decision will get made. Unlike science, the question is not whether the evidence is strong enough, but what course of action is best supported by the evidence. The core difference between inference for science and policy is in how we weigh the uncertainty.

While it may be unreasonable to expect policies to wait for the same level of certainty that is required for publication in peer reviewed journals, it is reasonable to expect a high level of rigor. To serve as a guide for policy, we have been developing an inferential framework for policy under the banner of *robust analytics.* The general notion is that a robust conclusion would not change if the analysis had been done in a reasonable but slightly different way. Robust analytics are based on roughly the same notion. In practical terms, this means: 

+ going to great lengths to characterize and quantify *uncertainty;* 

+ developing ensembles of policy scenarios such that while each scenario is sampled from the uncertainty at random, total uncertainty is covered by the ensemble; 

+ evaluating the policy advice that emerges from the ensemble of scenarios.  

Ideally, robust advice should includes a recommended course of action, but what the ensemble may not have a natural consensus. The robust advice would recommend a course of action, but it would include a discussion of alternative policies that appear to be nearly as good. Robust advice can be tenuous, but it must be well-supported. 

The natural complement to robust analytics is *adaptive management.* Since health policies are made and adjusted on monthly, annual, or multi-year cycles, it's possible to learn from a decision and adapt. (*As an aside, the focus of adaptive management is not medicine, but policies affecting populations, usually made by national ministries of health.*) The possibility of *learning* asks us to weigh how evidence *could* change our minds about something. Learning in repeated analysis is difficult, so we will need the concepts and methods to support it. Robust analytics and adaptive management ask us to think carefully about the *value of information,* and methods for identifying the value of data we lack. Ideally, robust policy advice would include a prioritized list of data gaps that could be filled to reduce uncertainty the next time a decision must be made. The iterative process of acting and learning is at the core of adaptive management. 

This website -- *Health Analytics for Robust Policy* -- is designed as a resource for people who want to develop, apply, and teach methods to support health policy using the principles of *robust analytics* or *adaptive management.* It is a guide to material -- concepts, ideas, algorithms, software, commentaries and lessons -- that can support robust analytics. The material is written in R-markdown in a style that could fall anywhere between lecture notes, a user's guide, vignettes that teach a single concept, or commentary. At the top of this page, the [HUB](hub.html) is an easy guide to the content. We don't want this to become a pseudo-journal, so we'll use a chatty tone and to introduce ideas that ought to be handled in greater depth in peer review publications (see the [Style Guide](HARP-Style-Guide.html)).


## Recent {.tabset .tabset-fade .tabset-pills}

### - 

**September 25, 2023** 

The core activities of this team are  **R**obust **A**nalytics for **M**alaria **P**olicy (RAMP) and Adaptive Malaria Control. Some of the ideas we need for RAMP were published recently in *Spatial Dynamics of Malaria Transmission* [@WuSL2023SpatialDynamics] -- you can read it online at [PLoS Comp Bio](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1010684){target="_blank"}. 

We developed a new mathematical and computational framework for malaria simulation modeling that was modular, flexible, and extensible. The modularity was enforced through rigorous interfaces describing blood feeding and parasite transmission; and egg laying and emergence. The article includes some new methods for building and analyzing models to ensure they would have the capability of dealing with *parasite dispersal* and *spatial heterogeneity.* A core motivation was that robust analytics should be done at the right level of complexity, so frameworks should facilitate **scalable complexity** to make it possible to extend or elaborate on models. 

The software has been implemented in two software packages: 

+ [exDE: Extensible Differential Equations for Mosquito-Borne Pathogen Modeling](https://dd-harp.github.io/exDE/){target="_blank"}. 
    
+ [MicroMoB: Microsimulation for mosquito-borne pathogens](https://dd-harp.github.io/MicroMoB/){target="_blank"}. 

We've been working on extending the functionality to include exogenous forcing by weather and malaria control. Check back later for new developments, and maybe for some tutorials. 

### Older 

**September 25, 2023** 

*Hello, World!* -- This website was born. New stuff goes in the other tab. Over time, as new stuff gets added, the old stuff goes above this in reverse chronological order. 


## Appendices {.tabset .tabset-fade .tabset-pills}

### Contributors 

+ David L Smith is a [Professor](https://depts.washington.edu/healthms/people/david-smith/){target="_blank"}  in the Department [Health Metrics Sciences](https://depts.washington.edu/healthms/){target="_blank"}, [School of Medicine](https://www.uwmedicine.org/school-of-medicine){target="_blank"}, [University of Washington](https://www.washington.edu/){target="_blank"}. It's a common name, so Dave curates his [Google Scholar Page](https://scholar.google.com/citations?user=KsqPjT8AAAAJ&hl=en). 

+ Austin R Carter is a research scientist at the Institute for Health Metrics and Evaluation, University of Washington.  

### Funding  

This research was supported by several grants: 

+ We gratefully acknowledge a grant from the Bill and Melinda Gates Foundation (INV 030600). The grant funds an active collaboration with Uganda's National Malaria Control Division. Adaptive Malaria Control implements research funded by several previous grants from BMGF. 

+ We gratefully acknowledge a grant to support development of **Adaptive Vector Control,** in collaboration with the *Bioko Island Malaria Elimination Project,*  the National Institute of Allergies and Infectious Diseases (R01 AI163398). 

+ Many of the ideas were developed through a grant from the National Institutes of Allergies and Infectious Diseases (2U19AI089674) that funded  [*Program for Resistance, Immunology, Surveillance, and Modeling of Malaria in Uganda* (PRISM)](https://www.niaid.nih.gov/research/east-africa-international-center-excellence-malaria-research){target="_blank"}, which was an [International Center of Excellence for Malaria Research (ICEMR)](https://www.niaid.nih.gov/research/excellence-malaria-research){target="_blank"}. 

+ Software to support modeling for West Nile Virus transmission dynamics and control in Harris County, Texas was funded by a grant from the National Science Foundation, Directorate for Technology, Innovation, and Partnerships (TIP) as part of the Convergence Accelerator Program (NSF 2040688)

+ The research grew out of mosquito working groups discussions as part of RAPIDD (Research and Policy for Infectious Disease Dynamics). Over that time, many of us benefitted from the unwavering support and inspiration of F. Ellis McKenzie. 

The funders had no role in the development of this material. 

### Refs 
